find_path(TIFF_INCLUDE_DIR NAMES tiff.h
	PATHS ${CONAN_INCLUDE_DIRS_LIBTIFF}
	NO_DEFAULT_PATH)

find_library(TIFF_LIBRARY NAMES ${CONAN_LIBS_LIBTIFF}
	PATHS ${CONAN_LIB_DIRS_LIBTIFF}
	NO_DEFAULT_PATH)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(TIFF
	REQUIRED_VARS TIFF_LIBRARY TIFF_INCLUDE_DIR
	FOUND_VAR TIFF_FOUND
)

set(TIFF_INCLUDE_DIRS ${TIFF_INCLUDE_DIR})
set(TIFF_LIBRARIES ${TIFF_LIBRARY})

mark_as_advanced(TIFF_INCLUDE_DIR TIFF_LIBRARY)
