set(_supported_components libodb sqlite pgsql)

foreach(_comp ${odb_FIND_COMPONENTS})
    if(NOT ";${_supported_components};" MATCHES _comp)
        set(odb_FOUND False)
        set(odb_NOTFOUND_MESSAGE "Unsupported component: ${_comp}")
    endif()
    include("${CMAKE_CURRENT_LIST_DIR}/odb_${_comp}Config.cmake")
endforeach()
set(odb_FOUND True)

set(PACKAGE_VERSION "2.4.0")

if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
  if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
    set(PACKAGE_VERSION_EXACT TRUE)
  endif()
endif()